In [1]:
!pip install afinn
from afinn import Afinn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting afinn
  Downloading afinn-0.1.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 KB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: afinn
  Building wheel for afinn (setup.py) ... done
  Created wheel for afinn: filename=afinn-0.1-py3-none-any.whl size=53448 sha256=d25387d3bfe73c4cdcbbe7eebab1897b4d9aa9d4b8f59389cd86c51caa18cfb5
  Stored in directory: /root/.cache/pip/wheels/79/91/ee/8374d9bc8c6c0896a2db75afdfd63d43653902407a0e76cd94
Successfully built afinn
Installing collected packages: afinn
Successfully installed afinn-0.1

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_apps = pd.read_csv('/content/googleplaystore_clean.csv')
df_reviews = pd.read_csv('/content/googleplaystore_user_reviews.csv')

In [4]:
df_apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          9660 non-null   float64
 3   Reviews         9660 non-null   int64
 4   Size            9660 non-null   object
 5   Installs        9660 non-null   int64
 6   Type            9660 non-null   object
 7   Price           9660 non-null   float64
 8   Content_Rating  9660 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 679.3+ KB

In [6]:
df_apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone

In [8]:
df_reviews.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [9]:
df_n = pd.read_csv('/content/n.xlsx - Sheet1.csv')
df_n[:5]

        faced
0       faces
1    abnormal
2     abolish
3  abominable
4  abominably

In [10]:
df_p = pd.read_csv('/content/p.xlsx - Sheet1.csv')
df_p[:5]

       abound
0     abounds
1   abundance
2    abundant
3  accessable
4  accessible

In [11]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [12]:
df_reviews.fillna(' ',inplace=True)

In [14]:
df_reviews['Translated_Review'] = df_reviews.Translated_Review.apply(str.lower)
df_reviews.head(5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,i like eat delicious food. that's i'm cooking ...,Positive,1.0,0.533333
1,10 Best Foods for You,this help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,,,,
3,10 Best Foods for You,works great especially going grocery store,Positive,0.4,0.875
4,10 Best Foods for You,best idea us,Positive,1.0,0.3

In [15]:
import string
def string_clean(sent):
 return sent.translate(str.maketrans('','',string.punctuation))

In [16]:
df_reviews['Translated_Review'] = df_reviews.Translated_Review.apply(string_clean)
df_reviews.head(5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,i like eat delicious food thats im cooking foo...,Positive,1.0,0.533333
1,10 Best Foods for You,this help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,,,,
3,10 Best Foods for You,works great especially going grocery store,Positive,0.4,0.875
4,10 Best Foods for You,best idea us,Positive,1.0,0.3

In [17]:
from collections import Counter
n = Counter ( list(df_n.faced) ) 
p = Counter ( list(df_p.abound) ) 

def sentiment_func(sent):
  c_sent = Counter(sent.split(' '))

  tot_n = n + c_sent
  tot_p = p + c_sent

  duplicates_n = Counter({k: c for k, c in tot_n.items() if c > 1})
  res_n = sum(duplicates_n.values()  )

  duplicates_p = Counter({k: c for k, c in tot_p.items() if c > 1})
  res_p = sum(duplicates_p.values()  )

  return (res_p - res_n) * 3

In [19]:
#df2 = df_reviews[['App','Translated_Review','Sentiment_Polarity']]

In [20]:
df['np_sentiments'] = df_reviews.Translated_Review.apply(sentiment_func)
df['afinn_sentiments'] = df_reviews.Translated_Review.apply( Afinn().score)

<ipython-input-20-589cfba5bd78>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['np_sentiments'] = df_reviews.Translated_Review.apply(sentiment_func)

In [29]:
df.sort_values(['App']).head(4)

,App,Translated_Review,Sentiment_Polarity,np_sentiments,afinn_sentiments
0,10 Best Foods for You,i like eat delicious food thats im cooking foo...,1.0,15,13.0
128,10 Best Foods for You,very good simply good,0.805,3,6.0
129,10 Best Foods for You,on test,0.0,0,0.0
130,10 Best Foods for You,good,1.0,6,3.0

In [24]:
#we joined two datasets and only rows that are common in both are displayed
df_merged = pd.merge(df, df_apps, how='inner', on='App')

In [25]:
df_merged.head()

,App,Translated_Review,Sentiment_Polarity,np_sentiments,afinn_sentiments,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating
0,10 Best Foods for You,i like eat delicious food thats im cooking foo...,1.0,15,13.0,HEALTH_AND_FITNESS,4.0,2490,3.8,500000,Free,0.0,Everyone 10+
1,10 Best Foods for You,this help eating healthy exercise regular basis,0.25,6,4.0,HEALTH_AND_FITNESS,4.0,2490,3.8,500000,Free,0.0,Everyone 10+
2,10 Best Foods for You,,,0,0.0,HEALTH_AND_FITNESS,4.0,2490,3.8,500000,Free,0.0,Everyone 10+
3,10 Best Foods for You,works great especially going grocery store,0.4,12,3.0,HEALTH_AND_FITNESS,4.0,2490,3.8,500000,Free,0.0,Everyone 10+
4,10 Best Foods for You,best idea us,1.0,6,3.0,HEALTH_AND_FITNESS,4.0,2490,3.8,500000,Free,0.0,Everyone 10+

Task3:For paid apps only list the top 5 highest and lowest sentiment numbers for afinn column with the name of the app and the app category **kalın metin**

Apps with their 5 highest afinn sentiment values

In [27]:
df_paid = df_merged['Type'] == 'Paid'
df_paid2 = df_merged[df_paid]
df_paid2.sort_values('afinn_sentiments',ascending=False).head(5)[['App','afinn_sentiments']]

                                App  afinn_sentiments
34106  Dr. Panda & Toto's Treehouse              39.0
34146  Dr. Panda & Toto's Treehouse              39.0
38445           Essential Anatomy 3              23.0
38405           Essential Anatomy 3              23.0
12651         Beautiful Widgets Pro              20.0

 Apps with their 5 lowest sentiment values

In [28]:
df_paid = df_merged['Type'] == 'Paid'
df_paid2 = df_merged[df_paid]
df_paid2.sort_values('afinn_sentiments',ascending=True).head(5)[['App','afinn_sentiments']]

                                  App  afinn_sentiments
10508                    BIG Launcher             -10.0
56025                      HD Widgets              -7.0
12670           Beautiful Widgets Pro              -6.0
12659           Beautiful Widgets Pro              -6.0
20058  Call of Duty:Black Ops Zombies              -5.0